# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables for default database name, user, and password
ENV POSTGRES_DB=vero_db
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=root
